create table "SA".FL_INSURANCE_SAMPLE
(
	POLICYID INTEGER not null primary key,
	STATECODE CHAR(4),
	COUNTY VARCHAR(128),
	EQ_SITE_LIMIT REAL,
	HU_SITE_LIMIT REAL,
	FL_SITE_LIMIT REAL,
	FR_SITE_LIMIT REAL,
	TIV_2011 REAL,
	TIV_2012 REAL,
	EQ_SITE_DEDUCTIBLE REAL,
	HU_SITE_DEDUCTIBLE REAL,
	FL_SITE_DEDUCTIBLE REAL,
	FR_SITE_DEDUCTIBLE REAL,
	POINT_LATITUDE REAL,
	POINT_LONGITUDE REAL,
	LINE VARCHAR(128),
	CONSTRUCTION VARCHAR(64),
	POINT_GRANULARITY INTEGER
)